# Use the official Node.js image as the base image
FROM node:16-alpine

#ENV NODE_OPTIONS=--openssl-legacy-provider


# Set the working directory
WORKDIR /app/

# # Copy package.json and package-lock.json files to the container
COPY frontend/package*.json ./

# Install dependencies
#RUN npm install

# build app for production with minification
WORKDIR /app/frontend

# Expose port 3000 to the Docker host
EXPOSE 3000

# see frontend/package.json:: "scripts": "dev" block
CMD ["npm", "run", "dev", "--inspect node_modules/.bin/nuxt"]