version: '3'

services:
  ## DB
  db:
    image: mysql:8
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
  ## wordpress
  wordpress:
    build: ./backend
    depends_on:
      - db
    volumes:
      - ./backend:/var/www/html/backend
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
  ## Nuxt
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile.dev
    ports:
      - "3030:3030"
      - "24678:24678"
    volumes:
      - ./frontend:/app/frontend
      #- ./frontend:/app/frontend
      #- ./frontend/!node_modules:/app/frontend
      #- ./frontend/!.nuxt:/app/frontend
      #- ./frontend/!.output:/app/frontend
      # - ./frontend/composables:/app/composables
      # - ./frontend/layouts:/app/layouts
      # - ./frontend/pages:/app/pages
      # - ./frontend/public:/app/public
      # - ./frontend/types:/app/types
      # - ./frontend/app.vue:/app/app.vue
      # - ./frontend/nuxt.config.ts:/app/nuxt.config.ts
      # - ./frontend/unocss.config.ts:/app/unocss.config.ts
    depends_on:
      - wordpress
  ## NGINX
  proxy:
    build: ./nginx
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - frontend
      - wordpress

volumes:
  db_data:


